src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
#[UniqueEntity(fields: ['email'])]


class Student implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;

    #[ORM\Column(length: 255,unique:true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];


    #[ORM\Column(length: 255)]
    private ?string $Gender = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 6,
    )]
    private ?string $Adress = null;

    #[ORM\Column]
    private ?int $Phone = null;

    #[ORM\Column(length: 255)]
    private ?string $Nationality = null;

    #[ORM\Column(length: 255)]
    private ?string $Password = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_of_birth = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $admission_date = null;

    #[ORM\ManyToOne(inversedBy: 'student')]
    private ?Parents $parents = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Media $image = null;

    #[Assert\File(
        maxSize: '4024k',
        mimeTypes: ['image/png', 'image/jpeg']
    )]

    protected $file;

    #[ORM\Column(length: 255 , unique:true)]
    #[Assert\Length(exactly: 6)]
    private ?string $admission = null;

    #[ORM\ManyToOne(inversedBy: 'students')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Classe $class = null;

    #[ORM\ManyToOne(inversedBy: 'students')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Parents $parent = null;

    public function getId(): ?int
    {
        return $this->id;
    }

     /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_STUDENT';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): static
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): static
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }


    public function getGender(): ?string
    {
        return $this->Gender;
    }

    public function setGender(string $Gender): static
    {
        $this->Gender = $Gender;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(string $Adress): static
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->Phone;
    }

    public function setPhone(int $Phone): static
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->Nationality;
    }

    public function setNationality(string $Nationality): static
    {
        $this->Nationality = $Nationality;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): static
    {
        $this->Password = $Password;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): static
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getAdmissionDate(): ?\DateTimeInterface
    {
        return $this->admission_date;
    }

    public function setAdmissionDate(\DateTimeInterface $admission_date): static
    {
        $this->admission_date = $admission_date;

        return $this;
    }

    public function getParents(): ?Parents
    {
        return $this->parents;
    }

    public function setParents(?Parents $parents): static
    {
        $this->parents = $parents;

        return $this;
    }

    public function getImage(): ?Media
    {
        return $this->image;
    }

    public function setImage(?Media $image): static
    {
        $this->image = $image;

        return $this;
    }

         /**
    * Get file
    * @return  
    */
    public function getFile()
    {
        return $this->file;
    }
    
    /**
    * Set file
    * @return $this
    */
    public function setFile($file)
    {
        $this->file = $file;
        return $this;
    }

    public function getAdmission(): ?string
    {
        return $this->admission;
    }

    public function setAdmission(string $admission): static
    {
        $this->admission = $admission;

        return $this;
    }

    public function __toString(){
        return $this->getAdmission().' - '.$this->FirstName . ' ' . $this->LastName;
    }

    public function getClass(): ?Classe
    {
        return $this->class;
    }

    public function setClass(?Classe $class): static
    {
        $this->class = $class;

        return $this;
    }

    public function getParent(): ?Parents
    {
        return $this->parent;
    }

    public function setParent(?Parents $parent): static
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

     /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Entity/Subject.php
<?php

namespace App\Entity;

use App\Repository\SubjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubjectRepository::class)]
class Subject
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Type = null;

    #[ORM\ManyToOne(inversedBy: 'subjects')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Classe $Class = null;

    #[ORM\OneToMany(mappedBy: 'Subject', targetEntity: Teacher::class)]
    private Collection $teachers;

    #[ORM\OneToMany(mappedBy: 'subject', targetEntity: Exam::class)]
    private Collection $exams;

    #[ORM\OneToMany(mappedBy: 'subject', targetEntity: ClassRoutine::class)]
    private Collection $classRoutines;

    public function __construct()
    {
        $this->teachers = new ArrayCollection();
        $this->exams = new ArrayCollection();
        $this->classRoutines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): static
    {
        $this->Type = $Type;

        return $this;
    }

    public function getClass(): ?Classe
    {
        return $this->Class;
    }

    public function setClass(?Classe $Class): static
    {
        $this->Class = $Class;

        return $this;
    }

    /**
     * @return Collection<int, Teacher>
     */
    public function getTeachers(): Collection
    {
        return $this->teachers;
    }

    public function addTeacher(Teacher $teacher): static
    {
        if (!$this->teachers->contains($teacher)) {
            $this->teachers->add($teacher);
            $teacher->setSubject($this);
        }

        return $this;
    }

    public function removeTeacher(Teacher $teacher): static
    {
        if ($this->teachers->removeElement($teacher)) {
            // set the owning side to null (unless already changed)
            if ($teacher->getSubject() === $this) {
                $teacher->setSubject(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return $this->Name;
    }

    /**
     * @return Collection<int, Exam>
     */
    public function getExams(): Collection
    {
        return $this->exams;
    }

    public function addExam(Exam $exam): static
    {
        if (!$this->exams->contains($exam)) {
            $this->exams->add($exam);
            $exam->setSubject($this);
        }

        return $this;
    }

    public function removeExam(Exam $exam): static
    {
        if ($this->exams->removeElement($exam)) {
            // set the owning side to null (unless already changed)
            if ($exam->getSubject() === $this) {
                $exam->setSubject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ClassRoutine>
     */
    public function getClassRoutines(): Collection
    {
        return $this->classRoutines;
    }

    public function addClassRoutine(ClassRoutine $classRoutine): static
    {
        if (!$this->classRoutines->contains($classRoutine)) {
            $this->classRoutines->add($classRoutine);
            $classRoutine->setSubject($this);
        }

        return $this;
    }

    public function removeClassRoutine(ClassRoutine $classRoutine): static
    {
        if ($this->classRoutines->removeElement($classRoutine)) {
            // set the owning side to null (unless already changed)
            if ($classRoutine->getSubject() === $this) {
                $classRoutine->setSubject(null);
            }
        }

        return $this;
    }

}

src/Controller/TeacherController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Teacher;
use App\Form\TeacherType;
use App\Form\TeacherUpdateType;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\Media;
use App\Form\TeacherSearchType;
use App\Model\TeacherSearch;

class TeacherController extends AbstractController
{

    public function index(EntityManagerInterface $em, PaginatorInterface $paginator, Request $request): Response
    {
        $teacherSearch = new TeacherSearch();

        $form = $this->createForm(TeacherSearchType::class,$teacherSearch);
        $form->handleRequest($request);

        $queryBuilder = $em->getRepository(Teacher::class)->createQueryBuilder('t');
        
        if($form->isSubmitted() && $form->isValid()){

            if(!empty($teacherSearch->admission)){
                $queryBuilder->Where('t.admissionId LIKE :admission')
                ->setParameter('admission', '%'.$teacherSearch->admission.'%');
            }

            if(!empty($teacherSearch->name)){
                $queryBuilder->andWhere('t.FirstName LIKE :name')
                ->setParameter('name','%'.$teacherSearch->name.'%');
            }

            if(!empty($teacherSearch->class)){
                $queryBuilder->andWhere('t.class = :class')
                ->setParameter('class',$teacherSearch->class);
            }
        }

        $query = $queryBuilder->getQuery();

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('teacher/index.html.twig',[
            'pagination' => $pagination,
            'form' => $form->createView()
        ]);

    }

    public function add(Request $request , EntityManagerInterface $em): Response
    {
        $teacher = new Teacher();

        $form = $this->createForm(TeacherType::class,$teacher);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            // Create new Media:
            $media = new Media();


            if($teacher->getFile()){

                $media->setFile($teacher->getFile());

                $media->upload($this->getParameter('files_directory'));   

                $em->persist($media);
                $em->flush();

            }else{
                
                $file_name = md5(uniqid());
                $file_name =  $file_name.".jpeg";
                
                if (!file_exists($this->getParameter('files_directory')."jpg/")) {
                    mkdir($this->getParameter('files_directory')."jpg/");
                }
                
                copy($this->getParameter('files_directory')."/../img/defaultProfile.jpg", $this->getParameter('files_directory')."jpg/".$file_name);

                sleep(1);

                $media->setTitle("defaultProfile.jpg");                  
                $media->setName($file_name);                    
                $media->setUrl($file_name);                    
                $media->setType("image/jpg");                
                $media->setExtension("jpg");                  
                
                $em->persist($media);
                $em->flush();
            }
            

            $teacher->setImage($media);
            
            $today = new \DateTime();
            $teacher->setJoiningDate($today);

            $em->persist($teacher);
            $em->flush();

            $this->addFlash('success','Teacher added successfully');

            return $this->redirectToRoute('app_teacher_index');
        }

        return $this->render('teacher/add.html.twig',[
            'form' => $form->createView()
        ]);
    }

    public function update(Request $request , EntityManagerInterface $em , Teacher $teacher): Response
    {

        $update_form = $this->createForm(TeacherUpdateType::class,$teacher);
        $update_form->handleRequest($request);

        if($update_form->isSubmitted() && $update_form->isValid()){
            
            if($teacher->getFile()){

                $media = new Media();
                $oldmedia = $teacher->getImage();

                $media->setFile($teacher->getFile());

                $media->upload($this->getParameter('files_directory'));

                $em->persist($media);
                $em->flush();

                $teacher->setImage($media);
                $em->flush();

                if($oldmedia){

                    $oldmedia->delete($this->getParameter('files_directory'));
                    
                    $em->remove($oldmedia);
                    $em->flush();  
                }
   
            } 
            $today = new \DateTime();
            $teacher->setJoiningDate($today);

            $em->persist($teacher);
            $em->flush();

            $this->addFlash('success','Teacher updated successfully.');

            return $this->redirectToRoute('app_teacher_index');
        }

        return $this->render('teacher/update.html.twig',[
            'form' => $update_form->createView()
        ]);
    }

    public function delete(EntityManagerInterface $em , Teacher $teacher)
    {
        $media = $teacher->getImage();

        $em->remove($teacher);
        $em->flush();

        if($media){
            $media->delete($this->getParameter('files_directory'));

            $em->remove($media);
            $em->flush();
        }

        $this->addFlash('success','Teacher deleted successfully');

        return $this->redirectToRoute('app_teacher_index');
    }
}

templates/teacher/add.html.twig
{% extends 'template.html.twig' %}

{% block title %}Teacher{% endblock %}

{% block path %}Add Teacher{% endblock %}

{% block content %}
{{ form_start(form) }}
<div class="bg-white rounded-xl w-full p-6 border shadow-sm">
    <h1 class="text-lg font-semibold">Teacher Information</h1>
    
    <div class="grid grid-cols-3 gap-6 py-4">
        <div>
            {{ form_label(form.firstName,'First Name',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.firstName,{'attr':{'class':'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light','placeholder':'Enter First Name'}}) }}
            {{ form_errors(form.firstName) }}
        </div>
        <div>
            {{ form_label(form.lastName,'Last Name',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.lastName,{'attr':{'class':'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light','placeholder':'Enter Last Name'}}) }}
            {{ form_errors(form.lastName) }}
        </div>
        <div>
            {{ form_label(form.gender,'Gender',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.gender,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}}) }}
            {{ form_errors(form.gender) }}
        </div>
        <div>
            {{ form_label(form.email,'Email',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.email,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500','placeholder':'Enter Email'}}) }}
            {{ form_errors(form.email) }}
        </div>
        <div>
            {{ form_label(form.admissionId,'Admission ID',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.admissionId,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500','placeholder':'Enter Admission ID'}}) }}
            {{ form_errors(form.admissionId) }}
        </div>
        <div>
            {{ form_label(form.dateOfBirth,'Date Of Birth',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.dateOfBirth,{'attr':{'class':'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light'}}) }}
            {{ form_errors(form.dateOfBirth) }}
        </div>
        <div>
            {{ form_label(form.adress,'Adress',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.adress,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500','placeholder':'Enter Adress'}}) }}
            {{ form_errors(form.adress) }}
        </div>
        <div>
            {{ form_label(form.phone,'Phone',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.phone,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500','placeholder':'Enter Phone'}}) }}
            {{ form_errors(form.phone) }}
        </div>
        <div>
            {{ form_label(form.class,'Class',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.class,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}}) }}
            {{ form_errors(form.class) }}        
        </div>
        <div>
            {{ form_label(form.Subject,'Subject',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.Subject,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}}) }}
            {{ form_errors(form.Subject) }}        
        </div>
        <div>
            {{ form_label(form.password.first,'Password',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.password.first,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500','placeholder':'********'}}) }}
            {{ form_errors(form.password.first) }}
        </div>
        <div>
            {{ form_label(form.password.second,'Repeat Password',{'label_attr':{'class':'block mb-1 text-sm font-medium text-gray-900 dark:text-white'}}) }}
            {{ form_widget(form.password.second,{'attr':{'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500','placeholder':'********'}}) }}
            {{ form_errors(form.password.second) }}
        </div>
    </div>

    <div class="mt-8">
        <div class="flex flex-col items-start gap-y-1">
            {{ form_label(form.file,'Upload Student Photo',{'label_attr':{'class':'"mb-2 font-semibold'}}) }}
            {{form_widget(form.file,{'attr':{'class':'"block w-full text-sm text-gray-500
            file:mr-4 file:py-2 file:px-4
            file:rounded-md file:border-0
            file:text-sm file:font-semibold
            file:bg-black/90 file:text-white
            hover:file:bg-black/80'}})}}
        </div>
    </div>

    <button type="submit" class="text-white mt-6 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-10 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Add New Teacher</button>
    <a href="{{ path('app_teacher_index') }}" class="mt-6 bg-black text-white focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-10 py-2.5 mr-2 mb-2">Back</a>
</div>
{{ form_end(form) }}
{% endblock %}